permalink: /posts/:title
markdown: kramdown
kramdown:
  math_engine: katex

plugins_dir:
  - jekyll-sitemap

title: nltr
name: Daniel Coble
url: https://dncoble.github.io
description: It's my website.
twitter: nileliketherivr
github: dncoble
github_owner_url: https://github.com/dncoble
github_owner_gravatar_url: https://avatars.githubusercontent.com/u/51173021?v=4
linkedin: https://www.linkedin.com/in/daniel-coble-5a2352241/
forthcoming: /forthcoming.html
